name: Trigger Jenkins Build

on:
  push:
    branches:
      - main

jobs:
  trigger-jenkins:
    runs-on: ubuntu-latest

    steps:
      - name: Trigger Jenkins Job
        run: |
          curl -X POST "https://nastier-leopoldo-nonadhering.ngrok-free.dev/job/UrlHealthMonitor-CI/build?token=jenkins-trigger" \
          --user AMOGH_MS:${{ secrets.JENKINS_TOKEN }}